# Generated by Django 5.0.3 on 2024-05-18 01:23

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='profile_images/default_profile_image.jpg', storage=profiles.models.ProfileImageFileStorage(), upload_to=profiles.models.create_name)),
                ('bio_text', models.CharField(blank=True, max_length=500)),
                ('is_public', models.BooleanField(default=True)),
                ('friends', models.ManyToManyField(blank=True, to='profiles.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
