# Generated by Django 5.0.3 on 2024-05-20 21:47

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/default/default_profile_image.jpg', storage=profiles.models.OverwriteFileStorage(), upload_to=profiles.models.create_name),
        ),
    ]
