# Each route describes how an incoming URL will be processed by Platform.sh.

"https://{default}/":
  type: upstream
  upstream: "project_ll:http"
  
"https://www.{default}/":
  type: redirect
  to: "https://{default}/"